# Generated by Django 6.0 on 2025-12-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_delete_epaperpdf_alter_news_reporter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='epaper/')),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
