# Generated by Django 6.0 on 2025-12-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_epaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epaper',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
