# Generated by Django 6.0 on 2026-07-17 06:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_epaper_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epaper',
            name='pdf',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='epaper/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
