# Generated by Django 6.0 on 2026-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_alter_epaper_pdf_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('position', models.CharField(choices=[('header', 'Header ke neeche'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('in_feed', 'News ke beech me')], default='sidebar', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
