# Generated by Django 6.0 on 2026-07-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 video (image ki jagah bhi use kar sakte ho)', null=True, upload_to='ads_videos/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
    ]
