# Generated by Django 6.0 on 2026-07-19 06:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_advertisement_video_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 video (image ki jagah bhi use kar sakte ho)', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='ads_videos/'),
        ),
    ]
